Mobile-menu
28919926/Portfolio-Mobile pull request #11
Opened 2022-09-06 15:16 UTC by 28919926

Add the eslint file for JavaScript.
Modify HTML and CSS files.
Modify the Hemberger to be responsive on the mobile version.
Add linter changes.

2022-09-06 15:43 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @28919926, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Good use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 15:43 UTC, leonardodiasb commented on style.css
> +    mix-blend-mode: normal;
- [x] Your mobile menu looks a little bit similar to the Figma design but it is not well styled for a mobile screen. The menu options are cut out of the screen and they don't have the same font-family, and colors as the template. Kindly fix these issues so it can create better visuals and the correct usage of the mobile menu.
 - [x] I would recommend you create a sticky or fixed mobile menu. It is possible to scroll down after the user clicks on the mobile menu on your application and he/she can accidentally leave the mobile menu which is not a good user experience. Kindly apply that to your project.
 -Your design:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/61919617/188676886-81a91cfe-a000-490c-a4bb-0c5f1fb36de4.png">
-Figma design:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/61919617/188677015-e59733ad-069a-432e-8877-2f9f4276a1b8.png">

2022-09-06 15:43 UTC, leonardodiasb commented on style.css
>  @media screen and (max-width: 768px) {
- [OPTIONAL] This is a project where we should follow a mobile first design so the desktop style should come after the mobile style. I would recommend you change the position of the code below this media query to above the media query you opened to style your mobile version so you don't need to have 2 media queries in your CSS file and follow the DRY best practices.

2022-09-07 06:19 UTC, 28919926 commented on style.css
> +    mix-blend-mode: normal;
Thanks for the recommendations and I have worked on them.

2022-09-07 06:43 UTC, Ismailco approved these changes
### Hi @28919926, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 07:42 UTC, merged