Portfolio-desktop
28919926/Portfolio-Mobile pull request #6
Opened 2022-08-25 15:44 UTC by 28919926

Add media queries to css file to make a desktop version of the project.
Modify form changes to fit the design of figma.
Make changes on HTML file.
Run linters and fix.

2022-08-25 16:18 UTC, BertrandConxy commented
Hello @28919926, Please sure that all linters are passing 🙏

2022-08-25 16:23 UTC, BertrandConxy reviewed
Hi @28919926 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that has some linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-26 07:38 UTC, frank1738 requested changes
Hi @28919926 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 07:38 UTC, frank1738 commented on style.css
> +@media screen and (min-width: 1500px) {
- [ ] Would you please use the required Desktop breakpoint in the CSS file `@media screen and (min-width: 768px`. It should not be more than `1440px` as anything above that would be an extra large screen.
- [ ]  Your `about me` cards appear to be aligned vertically. Would you please align them horizontally to match the Figma design  `Hint` Use `Flexbox`

### Your Design

![image](https://user-images.githubusercontent.com/98453979/186848301-f60a4d70-3011-4c02-b222-45e1359589a8.png)

### Figma design

![image](https://user-images.githubusercontent.com/98453979/186848433-d3db960e-e206-48d1-827b-d368ea478c63.png)

2022-08-26 08:56 UTC, levy002 approved these changes
Hi @28919926 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

## Status: APPROVED 🔥 🔥 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly remove the empty space at the bottom of the page
   
     - ### Your design
 
     ![image](https://user-images.githubusercontent.com/87197412/186867161-1d385d81-70a3-4a84-87da-0af221772690.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 09:00 UTC, merged